### ISSUE TITLE
Argument of type 'number | undefined' is not assignable to parameter of type 'number'.

### ISSUE THREAD

**Issue by georgiossalonad** [book-monkey4/iteration-1-event-bindings#4]
Error: src/app/book-details/book-details.component.html:23:36 - error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

23         *ngFor="let r of getRating(book.rating)"></i>
                                      ~~~~~~~~~~~

  src/app/book-details/book-details.component.ts:6:16
    6   templateUrl: './book-details.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component BookDetailsComponent.

Here is the Repo: https://github.com/georgiossalonad/book-monkey

And the code:
book-details.component.html
```
<div *ngIf="book">
  <h1>{{ book.title }}</h1>
  <h3 *ngIf="book.subtitle">{{ book.subtitle }}</h3>
  <div class="ui divider"></div>
  <div class="ui grid">
    <div class="four wide column">
      <h4>Autoren</h4>
      <ng-container *ngFor="let author of book.authors">
        {{ author }} <br>
      </ng-container>
    </div>
    <div class="four wide column">
      <h4>ISBN</h4>
      {{ book.isbn }}
    </div>
    <div class="four wide column">
      <h4>Erschienen</h4>
      {{book.published}}
    </div>
    <div class="four wide column">
      <h4>Rating</h4>
      <i class="yellow star icon" *ngFor="let r of getRating(book.rating)"></i>
    </div>
  </div>
  <h4>Beschreibung</h4>
  <p>{{book.description}}</p>
  <div class="ui small images">
    <img *ngFor="let thumbnail of book.thumbnails" [src]="thumbnail.url">
  </div>
  <button class="ui red button" (click)="showBookList()">
    Zurück zur Buchliste
  </button>
</div>
```

book-details.component.ts
```
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Book } from '../shared/book';

@Component({
  selector: 'bm-book-details',
  templateUrl: './book-details.component.html',
  styleUrls: ['./book-details.component.css']
})
export class BookDetailsComponent implements OnInit {
  @Input() book: Book;
  @Output() showListEvent = new EventEmitter<any>();

  ngOnInit(): void {
  }

  getRating(num: number) {
    return new Array(num);
  }

  showBookList(){
    this.showListEvent.emit();
  }

}
```

**Comment by fmalcher** [comment]
Schalte mal bitte den Strict Mode aus (Option "strict" und "strict"-Flags unter "angularCompilerOptions" in der tsconfig). Das Problem heute Vormittag dürfte damit dann auch erledigt sein.
Grundsätzlich ist der Strict Mode eine gute Sache, aber meiner Meinung nach sind einige der Regeln unnötig restriktiv und führen zu komplizierterem Code. Wir haben den Strict Mode für das Buch nicht vorgesehen.

An dieser Stelle kannst du das Problem natürlich auch beheben. book.rating ist in deinem Model optional. Du musst es dort also verpflichtend machen oder das Argument für deine Methode auch optional.

**Comment by georgiossalonad** [comment]
Nachdem ich den folgenden Eintrag in der `tsconfig.json` geändert habe, funktioniert der Code wieder:

```
"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    // "strictInjectionParameters": true,
    // "strictInputAccessModifiers": true,
    // "strictTemplates": true
  }
```

**Comment by fmalcher** [comment]
Wir haben uns das Thema Strict Mode einmal für die 4. Auflage notiert.
